[package]
name = "billflux-desktop"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = "2"

[dependencies]
tauri = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.38", features = ["bundled"] }
quick-xml = "0.42.0"
chrono = "0.4.45"


rfd = { version = "0.16.0", default-features = false }
